'use strict'

require('./scour/at_test')
require('./scour/boolean_test')
require('./scour/del_test')
require('./scour/extend_test')
require('./scour/extensions_test')
require('./scour/filter_test')
require('./scour/filter_advanced_test')
require('./scour/filter_function_test')
require('./scour/first_test')
require('./scour/for_each_test')
require('./scour/gather_test')
require('./scour/go_test')
require('./scour/last_test')
require('./scour/len_test')
require('./scour/null_values_in_scope_test')
require('./scour/null_values_test')
require('./scour/reject_test')
require('./scour/set_test')
require('./scour/sort_by_collision_test')
require('./scour/sort_by_dot_test')
require('./scour/sort_by_shuffled_test')
require('./scour/sort_by_test')
require('./scour/to_array_test')
require('./todo_test')
