'use strict'

require('./tape/at_test')
require('./tape/boolean_test')
require('./tape/del_test')
require('./tape/extend_test')
require('./tape/extensions_test')
require('./tape/filter_test')
require('./tape/first_test')
require('./tape/for_each_test')
require('./tape/go_test')
require('./tape/len_test')
require('./tape/reject_test')
require('./tape/sort_by_shuffled_test')
require('./tape/to_array_test')
